### ISSUE TITLE
ImportError: No module name pymarkovchain

### ISSUE THREAD

**Issue by GT-SEGFAULT** [eon8ight/shitpost-learner#1]
Trying to run the shitposter, got this error:

Traceback (most recent call last):
  File "C:\Users\Caleb\Desktop\shitpost-learner-master\shitposter.py", line 6, in <module>
    from pymarkovchain import MarkovChain
ImportError: No module named pymarkovchain

**Comment by eon8ight** [comment]
Run 'sudo pip install PyMarkovChain', should've added in readme - will add to readme when I get back to my PC
